# Application Name
spring.application.name=FoodOrderingSystem

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/food_ordering_db
spring.datasource.username=postgres  # or your PostgreSQL username
spring.datasource.password=Keyin2021  # replace with your actual password
spring.datasource.driver-class-name=org.postgresql.Driver  # PostgreSQL driver

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update  # Automatically update the schema
spring.jpa.show-sql=true  # Show SQL queries in the console
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect  # Use PostgreSQL dialect
